### ISSUE TITLE
posun casu

### ISSUE THREAD

**Issue by rossowl** [krejcipetr/sledovanitv#2]
Máte tam chybu. Časové pasmo nelze řešit jen pomocí +0100, protože se střídá letní a standartní čas.
Co zkusit toto:
timezone = pytz.timezone('Europe/Prague')
start = timezone.localize(datetime.strptime(item['startTime'], '%Y-%m-%d %H:%M'))
stop = timezone.localize(datetime.strptime(item['endTime'], '%Y-%m-%d %H:%M'))
programme = etree.SubElement(root, 'programme', channel=key, start=start.strftime('%Y%m%d%H%M%S %z'), stop=stop.strftime('%Y%m%d%H%M%S %z'))

Pak vám bude fungovat i nahrávání v pravý čas.
Názvy proměnných si musíte upravit podle sebe, protože jsem to celé musel předělat.
Ale díky moc za URL na api sledovanitv.cz

**Comment by krejcipetr** [comment]
Ja vim, problem mam s instalaci knihovny na CoreElec. Ale doufam, ze se to casem podari vyresit.

**Comment by Vasek79** [comment]
@rossowl mohl byste tu svou upravu zveřejnit? Běží mi to na linuxu, takže s knihovnami bych problém mít neměl a přiznám se, že jsem neznalý toho, abych si to překopával sám. Dík

**Comment by Vasek79** [comment]
Mám ještě jednu, pro vás asi hloupou otázku, ale když se podívám na sledovanitv.cz/api/epg, tak tam vidím startTime a stopTime správně, tak proč je nutné ten čas potom pro TVH nějak posouvat? Nějak mi to nedochází.

**Comment by rossowl** [comment]
Jestli vidíte v Tvheadendu čas začátku a konce pořadu správně, tak nic nedělejte. Mám dojem, že TVHeadend bere čas v UTC, v xmltv je potřeba vložit datum a čas s časovým pásmem a po posunu času to nesedí (UTC je jen jeden).
Pokud už máte svoje device a password registrované na sledovanitv a váš tvheadend jede na linuxu (debian, ubuntu), kde si můžete libovolně instalovat balíčky, můžete zkustit tento skript:
https://github.com/rossowl/stvh
Je to jeden soubor, který kromě registrace dělá všechno, tzn. playlist, epg pro xmltv a přehrává pomocí ffmpeg pipe. Registraci jsem nedělal, protože zařízení už mám registrováno. Device ID a Password musíte vložit do toho .py souboru. Pokud máte pin a je vám +18, tak klidně i pin.
Napsal jsem to za dvě hodinky večer, od té doby mi to jede v tvheadend bez problému.
U řešení krejcipetr mi vadil ten bucket, protože mám více IPTV sítí, jeden DVB-T2 tuner a pořád se mi přehazovalo pořadí programů. Taky mi občas kanály nejely, protože vypršel token a nestihl se přegenerovat playlist. Tohle jede, playlist stačí vygenerovat jednou za čas, když se objeví nový kanál. Aby to tvheadend načetl, musíte vždy změnit název souboru playlistu nebo ještě lépe, vystavit ho pod apache webserver a na konec cesty k němu měnit jen query string např. http://tvh.local/playlist.m3u?v=2 , tím v= pak označujete verze playlistu a přinutíte tvheadend, aby ho znova načetl. Čísla programů se nezmění.
Kdybyste potřeboval dodělat registraci nebo nějakou úpravu našel nějakou chybu, napište do toho repozitáře issue a já na to někdy večer mrknu.

**Comment by krejcipetr** [comment]
protoze  čas v xmltv se očekává se zónou, pokud tam zóna není, tak THV  si myslí, že je v GMT zóně a čas posune. čas se neupravuje pouze se doplní zóna. zóna je napevno protože se mi na coreelec nepodařilo zprovoznit pytz modul.Dne 1. 4. 2020 14:11 napsal uživatel Vasek79 <notifications@github.com>:

Mám ještě jednu, pro vás asi hloupou otázku, ale když se podívám na sledovanitv.cz/api/epg, tak tam vidím startTime a stopTime správně, tak proč je nutné ten čas potom pro TVH nějak posouvat? Nějak mi to nedochází.



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

Dne 1. 4. 2020 14:11 napsal uživatel Vasek79 <notifications@github.com>:

Mám ještě jednu, pro vás asi hloupou otázku, ale když se podívám na sledovanitv.cz/api/epg, tak tam vidím startTime a stopTime správně, tak proč je nutné ten čas potom pro TVH nějak posouvat? Nějak mi to nedochází.



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

Dne 1. 4. 2020 14:11 napsal uživatel Vasek79 <notifications@github.com>:

Mám ještě jednu, pro vás asi hloupou otázku, ale když se podívám na sledovanitv.cz/api/epg, tak tam vidím startTime a stopTime správně, tak proč je nutné ten čas potom pro TVH nějak posouvat? Nějak mi to nedochází.

**Comment by mk01** [comment]
time vie tiez vratit casove pasmo:

```
local = time.strftime("%z")
```
